# Generated by Django 4.1 on 2022-09-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans', to='roaster.roaster'),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roaster', to='roaster.user'),
        ),
    ]
