# Generated by Django 4.1 on 2022-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0002_alter_bean_roaster_alter_roaster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
