# Generated by Django 4.1 on 2022-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0003_roaster_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='bean_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bean',
            name='organic',
            field=models.BooleanField(default=False),
        ),
    ]
