# Generated by Django 4.1 on 2022-09-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0004_bean_bean_type_bean_organic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('site_url', models.CharField(max_length=100)),
                ('logo_pic', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beans_list', to='roaster.roaster'),
        ),
        migrations.AddField(
            model_name='bean',
            name='retailer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='beans_inventory', to='roaster.retailer'),
        ),
    ]
