# Generated by Django 4.1 on 2022-09-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0005_retailer_alter_bean_roaster_bean_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='retailer',
        ),
    ]
