# Generated by Django 4.1 on 2022-09-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0006_remove_bean_retailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
