# Generated by Django 4.1 on 2022-09-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0007_delete_retailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('site_url', models.CharField(max_length=100)),
                ('logo_pic', models.CharField(blank=True, max_length=200)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bean_inventory', to='roaster.bean')),
            ],
        ),
    ]
