# Generated by Django 4.1 on 2022-09-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0008_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='bean',
        ),
    ]
