# Generated by Django 4.1 on 2022-09-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roaster', '0009_remove_retailer_bean'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
