# Generated by Django 4.1.1 on 2022-09-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icdb2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='roaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beans_list', to='icdb2.roaster'),
        ),
    ]
