# Generated by Django 4.1.1 on 2022-09-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='bean',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_list', to='coffee2.bean'),
        ),
    ]
